CREATE DATABASE housecd;

CREATE TABLE housecd.t_user(
  userId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  userName VARCHAR(255) NOT NULL ,
  PASSWORD VARCHAR(255) NOT NULL ,
  phone VARCHAR(255) NOT NULL
) ENGINE=INNODB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE housecd.app_info(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  appName VARCHAR(255),
  appId VARCHAR(255) NOT NULL ,
  appSecret VARCHAR(255) NOT NULL ,
  appStatus VARCHAR(255) NOT NULL,
  phone VARCHAR(255),
  crtTime TIMESTAMP ,
  rcntlyTime TIMESTAMP
) ENGINE=INNODB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;